### ISSUE TITLE
ClojureScript?

### ISSUE THREAD

**Issue by cassiel** [stathissideris/spectacles#3]
Any reason why this can't be ported to ClojureScript?

**Comment by stathissideris** [comment]
This relies solely on clojure.spec.alpha and it doesn't even have any macros, so a cljs port would be dead easy.

**Comment by cassiel** [comment]
I have a ClojureScript version working. There are minor hassles with things like `eval`, and I don't have the test set machinery for the ClojureScript side yet, but it seems usable.

**Comment by stathissideris** [comment]
Do you have any ideas about what could be done for `eval`? I really don't see how it could be avoided!

**Comment by stathissideris** [comment]
Unless the feature of checking `s/map-of` is skipped in cljs...

**Comment by stathissideris** [comment]
Done, I just added a note that `map-of` behaves differently.
